# Generated by Django 6.0.7 on 2026-07-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='posts/', verbose_name='fichier'),
        ),
    ]
